export const ISVALIDNAME = "ISVALIDNAME";
export const ISVALIDPHONE = "ISVALIDPHONE";
export const ISVALIDEMAIL = "ISVALIDEMAIL";
export const ISVALIDMESSAGE = "ISVALIDMESSAGE";
export const ISVALIDFORM = "ISVALIDFORM";
export const RESETFORMCONTACTUS = "RESETFORMCONTACTUS";
export const ISVALIDADDRESS = "ISVALIDADDRESS";